# Generated by Django 2.0.3 on 2018-04-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('image', models.ImageField(upload_to='Pictures')),
            ],
        ),
    ]
